# Generated by Django 4.2.11 on 2024-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100, unique=True)),
                ('orderName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], max_length=50)),
            ],
        ),
    ]
